logistics:
  expectedIncomeDecrease:
    30: 5
    60: 10
    120: 15
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cubix-logistics
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
logging:
  level:
    org:
      springframework : INFO

